{{- if not .Values.postgresql.enabled }}
{{- if not .Values.externalPostgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-external-db-secret
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalPostgresql.password | default "" | b64enc | quote }}
{{- end }}
{{- end }}
